image: prusa/sl1fw

stages:
  - build
  - test
  - i18n
  - deploy

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - git submodule update --init --recursive

build:
  stage: build
  script:
    - python3 setup.py build

mcsim:
  stage: build
  script:
    - sh build_sim.sh
  artifacts:
    paths:
      - SLA-control-01.elf

pot:
  stage: build
  script:
    - make -C slafw/locales extract
    - cp slafw/locales/slafw.pot ./
  artifacts:
    paths:
      - slafw.pot

sphinx:
  stage: build
  only:
    refs:
      - master
  artifacts:
    paths:
      - documentation/*
  script:
    - sh builddoc.sh
    - mv doc/build documentation

unittest:
  stage: test
  dependencies:
    - mcsim
  script:
    - sh unittest.sh

integration:
  stage: test
  dependencies:
    - mcsim
  script:
    - sh integrationtest.sh

pylint:
  stage: test
  dependencies: []
  script:
    - sh pylint.sh

mypy:
  stage: test
  dependencies: []
  script:
    - sh mypy.sh

i18n-complete:
  stage: i18n
  dependencies:
    - pot
  script:
    - make --keep-going -C slafw/locales check
  allow_failure: true

pot-deploy:
  stage: deploy
  dependencies:
    - pot
  only:
    refs:
      - master
      - /[0-9]*\.[0-9]*/
  script:
    - cp slafw.pot ${CI_COMMIT_REF_NAME}-slafw.pot
    - >
        lftp -c "
        set sftp:ssl-force yes;
        open -u ${DEPLOY_FTP_USER},${DEPLOY_FTP_PASS} ${DEPLOY_FTP_HOST};
        put -O ${DEPLOY_FTP_DEST} ${CI_COMMIT_REF_NAME}-slafw.pot;
        "

pages:
  stage: deploy
  dependencies:
    - sphinx
    - pot
  script:
    - mv documentation public
    - mv slafw.pot public/
  artifacts:
    paths:
      - public
  only:
    refs:
      - master

