image: prusa/sl1fw

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd firmware
    - python2 setup.py build
    - python3 setup.py build

test:
  stage: test
  script:
    - cd firmware
    - python2 -m unittest discover sl1fw.tests
    - python3 -m unittest discover sl1fw.tests

