image: prusa/sl1fw

stages:
  - build
  - test
  - deploy

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - cat ~/.ssh/known_hosts

build:
  stage: build
  script:
    - cd firmware
    - python3 setup.py build

mcsim:
  stage: build
  script:
    - git clone --single-branch --branch master --depth 1 git@gitlab.com:prusa3d/sl1/mc-fw.git
    - BOARD=6 SIMULATION=1 make -C mc-fw/SLA-control-01 -j5
    - mv mc-fw/SLA-control-01/SLA-control_rev06.elf ./SLA-control-01.elf
  artifacts:
    paths:
      - SLA-control-01.elf

pot:
  stage: build
  script:
    - make -C firmware/sl1fw/locales extract
    - cp firmware/sl1fw/locales/sl1fw.pot ./
  artifacts:
    paths:
      - sl1fw.pot
  only:
    refs:
      - master
      - /[0-9]*\.[0-9]*/

sphinx:
  stage: build
  only:
    refs:
      - master
  artifacts:
    paths:
      - documentation/*
  script:
    - sphinx-build -b html firmware/doc/ firmware/doc/build
    - mv firmware/doc/build documentation

unittest:
  stage: test
  dependencies:
    - mcsim
  script:
    - export PATH="${PATH}:$(pwd)"
    - cd firmware
    - python3-coverage run -m unittest discover --failfast --verbose sl1fw.tests.unittests
    - python3-coverage report --include "sl1fw*"

integration:
  stage: test
  dependencies:
    - mcsim
  script:
    - export PATH="${PATH}:$(pwd)"
    - cd firmware
    - python3 -m unittest discover --failfast --verbose sl1fw.tests.integration

pylint:
  stage: test
  dependencies: []
  script:
    - cd firmware
    - python3 -m pylint --version
    - python3 -m pylint --persistent=n --jobs 0 --additional-builtins=_,N_,ngettext --max-line-length=120 --disable similarities,bad-continuation,bad-whitespace,invalid-name,missing-docstring,bare-except,fixme,broad-except,line-too-long,too-many-instance-attributes,too-many-public-methods,too-many-locals,too-many-statements,too-few-public-methods,no-else-return,too-many-branches,too-many-arguments,protected-access,too-many-ancestors,wrong-import-order,too-many-lines,too-many-nested-blocks,too-many-return-statements,wrong-import-position,duplicate-code,cyclic-import,inconsistent-return-statements sl1fw

i18n-complete:
  stage: test
  dependencies:
    - pot
  only:
    refs:
      - /[0-9]*\.[0-9]*/
  script:
    - make --keep-going -C firmware/sl1fw/locales check
  allow_failure: true

pot-deploy:
  stage: deploy
  dependencies:
    - pot
  only:
    refs:
      - master
      - /[0-9]*\.[0-9]*/
  script:
    - cp sl1fw.pot ${CI_COMMIT_REF_NAME}-sl1fw.pot
    - >
        lftp -c "
        set sftp:ssl-force yes;
        open -u ${DEPLOY_FTP_USER},${DEPLOY_FTP_PASS} ${DEPLOY_FTP_HOST};
        put -O ${DEPLOY_FTP_DEST} ${CI_COMMIT_REF_NAME}-sl1fw.pot;
        "

pages:
  stage: deploy
  dependencies:
    - sphinx
    - pot
  script:
    - mv documentation public
    - mv sl1fw.pot public/
  artifacts:
    paths:
      - public
  only:
    refs:
      - master

